/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ScanRecord = IDL.Record({
  'id' : IDL.Nat,
  'imageNote' : IDL.Opt(IDL.Text),
  'confidenceScore' : IDL.Nat,
  'diseaseName' : IDL.Text,
  'timestamp' : Time,
  'cropType' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'clearHistory' : IDL.Func([], [], []),
  'getScanById' : IDL.Func([IDL.Nat], [ScanRecord], ['query']),
  'getScanCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getScanHistory' : IDL.Func([], [IDL.Vec(ScanRecord)], ['query']),
  'saveScan' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ScanRecord = IDL.Record({
    'id' : IDL.Nat,
    'imageNote' : IDL.Opt(IDL.Text),
    'confidenceScore' : IDL.Nat,
    'diseaseName' : IDL.Text,
    'timestamp' : Time,
    'cropType' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'clearHistory' : IDL.Func([], [], []),
    'getScanById' : IDL.Func([IDL.Nat], [ScanRecord], ['query']),
    'getScanCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getScanHistory' : IDL.Func([], [IDL.Vec(ScanRecord)], ['query']),
    'saveScan' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };